## From Suraj Batch 2

In [2]:
# Create a NumPy array of integers from 0 to 10.
import numpy as np
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Create an array of 10 zeros and change the 5th value to 1.
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
# Generate an array of 10 ones.
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
# Create a 1D array of 20 equally spaced numbers between 0 and 1.
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [44]:
# Create a 3x3 identity matrix.
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Create a 4x4 matrix with values from 0 to 15.
np.arange(16).reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
# Generate a 5x5 matrix with random values.
np.random.rand(5, 5)

array([[0.06723736, 0.24262103, 0.69947535, 0.36097203, 0.53618266],
       [0.81194625, 0.0268582 , 0.79408119, 0.84334712, 0.41200489],
       [0.72675673, 0.99280936, 0.00536036, 0.46399455, 0.83777297],
       [0.82449785, 0.6397606 , 0.67141381, 0.90614767, 0.4006039 ],
       [0.39117269, 0.62174049, 0.19794364, 0.56769324, 0.45582227]])

In [17]:
# Reverse the elements of an array.
a = np.arange(16)
a[::-1]

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [22]:
# Flatten a 2D array to 1D.
a = np.arange(9).reshape(3,3)
print(a)
a.flatten()

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Extract even numbers from an array.
a = np.arange(16)

print(f"Even numbers from the array{a} are:\n")
for i in a:
    if a[i]%2==0:
        print(a[i])

Even numbers from the array[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] are:

0
2
4
6
8
10
12
14
