In [4]:
# Numpy Basic
#----------------------------------

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3],[ 4, 5, 6]])

print(arr)
print(arr2)

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
(5,)
1
5
int64
